### PR TITLE
Update Comments UI and add support to post a comment

### PR DESCRIPTION
**Pull request by Quillraven**
I replaced the `Accordion` with a `GridList` and split the comments now into three areas:

- header: contains the amount of comments. Could later on be enhanced to add a filter functionality
- add new coment: text area to enter a new comment and button to post it. The button is only active when a text is entered. The text area gets cleared when a comment is successfully posted
- comments area: shows all comments sorted by the backend. The latest comment appears at the top.

Header and comments area get automatically updated when a new comment is posted.

How are strings usually handled in such a case because e.g. when I enter a "%" character then it cannot be send to the server. Also, newlines seem to disappear on the frontend. I guess it is because they are stored as "\n" on the server and in html we need "<\br>"?

I assume there are already utility functions for such things available?

----

image

image

image

### CODE REVIEW

**Comment by Quillraven** [comment]
Fixed the problem with special characters and newlines. They are now properly posted and displayed.

- URL decoding is no longer necessary in `createAndLink` function of `CommentService`. I don't know why but I guess Spring is automatically decoding strings if they are properly encoded
- Changed encoding in `ToiletService` of frontend from `encodeURI` to `encodeURIComponent`
- Added the `whiteSpace: "pre-wrap"`  style to the comments div to properly handle newlines

image

**Comment by Quillraven** [comment]
Also, added now a visual feedback for success and errors.

image

image

**Comment by Quillraven** [comment]
As discussed, the information is now sent via the body instead via query parameters.

We have now a little mix, which we should clean up most likely ;)

- PreviewImageController post: wrap toiletId and file into a "UploadImageDto" body?
- ToiletController put: remove id because it is already part of the toilet request body?
  - Maybe we should introduce here a "CreateUpdateToiletDto" as well for both post and put?

**Comment by christian-baumann** [comment]
I have pushed the following changes:

**Dev mode:**

By setting the system property `-Dtoilapp.devmode=true` as VM argument the dev mode can be activated. If the dev mode is activated `UserServer.getCurrentUserId()` returns a default dev user with the object id `123456789`. This dev user is also created by the `DataLoaderApplication`. Having a dev mode is convenient during development as soon as authentication is implemented.

**Other changes:**

The generate `GridFsImageService` had a dependency on `ToiletService` which is wrong, as "general purpose" services never must have dependencies on specific domain services. This also led to a circular dependency with `ToiletService`. I have resolved it by moving  `createAndLinkImage` to `ToiletService`. 

Furthermore I have changed the lazyinit field injection within the services to constructor injection. Please never use field injection without a good reason, but constructor injection for mandatory dependencies and method injection for optional dependencies.

Please, review my changes and merge the PR, if ok.

**Comment by Quillraven** [comment]
@christian-baumann: Reviewed and merged the PR after some minor adjustments. The existing unit tests did not run anymore due to the constructor changes. The tests are for sure old and not perfect but they should at least run without errors ;)

What about my two points from above?

- PreviewImageController post: wrap toiletId and file into a "UploadImageDto" body?
- ToiletController put: remove id because it is already part of the toilet request body?
  - Maybe we should introduce here a "CreateUpdateToiletDto" as well for both post and put?

**Comment by christian-baumann** [comment]
> PreviewImageController post: wrap toiletId and file into a "UploadImageDto" body.
In this case I would leave it as it is, because toiletId will never be stored and files are transferred in a different way and therefore custom code would be needed to encode the file content within a JSON object (e.g. Base64, etc.)

> ToiletController put: remove id because it is already part of the toilet request body?
Yes, makes sense. The same CreateUpdateToiletDto should also be used for create (POST).

**Pull request merged**
